// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // provider is defined in schema.prisma
    url: env("DATABASE_URL"),
    // @ts-expect-error: directUrl is required by Prisma 7 but missing in type definition
    directUrl: env("DIRECT_URL"),
  },
});
